### ISSUE TITLE
Sharing credentials between phone client & pwdsphinx client doesn't work for me (2nd round)

### ISSUE THREAD

**Issue by rolfschr** [dnet/androsphinx#9]
Hi,

I have an issue similar to #8. The setup is the same: I setup the software (8fddb9aab0d148520c29c050af814a35f24a6a37) on my phone and I also setup an oracle server (from https://github.com/stef/pwdsphinx, 7fde7bbcb91b83f035c5d5783f6fedb15e58ca1d). I used libsphinx 51b0c18c94b645bd7ea3bb21aef623318e0b7939 and equihash d4657dcb588ae852f8ab5c777837b0578caa3ffb. The pwdsphinx server works fine on my local machine (i.e. I can run the oracle process and access it using the python sphinx.py client). I have used these commands here stef/pwdsphinx#9 to generate the ssl certificate.

Here is a screenshot of the problem. On the left the oracle process, on the right the Python client ("connection from 127.0.0.1"). The client is able to create a password and receive it. Trying to receive the password from the phone ("connection from 192.168.178.50", last line) doesn't yield anything. The phone says "No users found for his host" (note the [typo](https://github.com/dnet/androsphinx/blob/c1432319bf1986c1c2e5ed5ad0129d329fc07452/app/src/main/res/values/strings.xml#L23) btw ...). The oracle output stays empty.

![image](https://user-images.githubusercontent.com/1188465/132341822-a618ae45-cfce-4518-933f-b89e326873c8.png)
(Note: The screenshot was taken a second before the "remove pid XXXXX" output.)

Similarly, when I try to create an entry from the phone client, I get this:

![image](https://user-images.githubusercontent.com/1188465/132342764-46a380d9-5d5b-4361-9431-07cd9cecbd5b.png)

(The phone says: "A server error occured.")

Happy to provide further details.

**Comment by rolfschr** [comment]
@stef This is probably for you, too.

**Comment by stef** [comment]
the server had some changes since the last release of androsphinx, and thus androsphinx needs to implement those changes to make it compatible with the backward incompatible changes. we hope that these are the last such changes.

**Comment by rolfschr** [comment]
Hi,

looks like there haven't been any updates for this. Do you already know when the changes will get implemented?

Thanks

**Comment by dnet** [comment]
@rolfschr sorry for the delay, as of b710b8d Python and Android implementations are in sync again

**Comment by dnet** [comment]
addendum: if you want to try with (the non-default) `rwd_keys=True` setting, use at least ab86a10 as it contains a fix regarding that configuration
